apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-processor
  namespace: logging
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::641875867446:role/multi-tenant-logging-ocp-cluster-processor-role